# Generated by Django 6.0.6 on 2026-06-10 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repertoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('composer', models.CharField(max_length=255)),
                ('arranger', models.CharField(blank=True, max_length=255, null=True)),
                ('target_voice', models.CharField(choices=[('G', 'General/All'), ('S', 'Soprano'), ('A', 'Alto'), ('T', 'Tenor'), ('B', 'Bass')], default='G', max_length=1)),
                ('pdf_score_url', models.URLField(blank=True, help_text='Link to sheet music PDF', max_length=500, null=True)),
                ('audio_track_url', models.URLField(blank=True, help_text='Link to learning track audio file', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_part', models.CharField(choices=[('S', 'Soprano'), ('A', 'Alto'), ('T', 'Tenor'), ('B', 'Bass')], max_length=1)),
                ('address_line_1', models.CharField(max_length=255)),
                ('town_city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('gift_aid_consent', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(default='Main Rehearsal Hall', max_length=255)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('pieces_covered', models.ManyToManyField(blank=True, to='choir.repertoire')),
            ],
        ),
    ]
