# Generated by Django 6.0.6 on 2026-06-10 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('voice_part', models.CharField(choices=[('soprano', 'Soprano'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('baritone', 'Baritone'), ('bass', 'Bass')], max_length=20)),
                ('experience', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general', 'General Enquiry'), ('booking', 'Concert Booking')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Enquiries',
            },
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='gift_aid_consent',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='town_city',
        ),
        migrations.RemoveField(
            model_name='repertoire',
            name='arranger',
        ),
        migrations.RemoveField(
            model_name='repertoire',
            name='audio_track_url',
        ),
        migrations.RemoveField(
            model_name='repertoire',
            name='pdf_score_url',
        ),
        migrations.RemoveField(
            model_name='repertoire',
            name='target_voice',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='repertoire',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly name (e.g., mozart-requiem)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='voice_part',
            field=models.CharField(blank=True, choices=[('S', 'Soprano'), ('A', 'Alto'), ('T', 'Tenor'), ('B', 'Bass')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='repertoire',
            name='composer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='repertoire',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REH', 'Standard Rehearsal'), ('RES', 'Cathedral Residency / Performance')], default='REH', max_length=3)),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(default="St Laurence's Church", max_length=200)),
                ('additional_notes', models.TextField(blank=True)),
                ('pieces', models.ManyToManyField(blank=True, related_name='events', to='choir.repertoire')),
            ],
        ),
        migrations.CreateModel(
            name='GiftAidDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=200)),
                ('town_city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('consent_given', models.BooleanField(default=False)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='choir.memberprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LearningAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voice_part', models.CharField(choices=[('SOP', 'Soprano'), ('ALT', 'Alto'), ('TEN', 'Tenor'), ('BAS', 'Bass'), ('ALL', 'Full Choir / PDF Score')], max_length=3)),
                ('asset_name', models.CharField(help_text='e.g., YouTube Practice Track or PDF Score', max_length=150)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='learning_assets/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('repertoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='choir.repertoire')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_paid', models.DateField()),
                ('term_reference', models.CharField(help_text='e.g., Autumn 2026 or Annual 26/27', max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='choir.memberprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Rehearsal',
        ),
    ]
