# Generated by Django 6.0.6 on 2026-06-22 08:28

from django.db import migrations


def update_site_domain(apps, schema_editor):
    # Grab the Site model dynamically from the historical apps registry
    Site = apps.get_model("sites", "Site")

    # Safely get or create ID 1 to overwrite example.com
    site, created = Site.objects.get_or_create(id=1)
    site.domain = "clentconsort.org"
    site.name = "Clent Consort"
    site.save()


class Migration(migrations.Migration):
    dependencies = [
        ("choir", "0002_auditionapplication_enquiry_and_more"),
    ]

    operations = [
        migrations.RunPython(update_site_domain),
    ]
