# Generated by Django 6.0.6 on 2026-06-22 22:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0004_attendance_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='additional_notes',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
