# Generated by Django 6.0.6 on 2026-06-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0005_alter_event_additional_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='consent_audio_video',
            field=models.BooleanField(default=False, help_text='I consent to being included in audio and video recordings for promotional purposes.'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='consent_photography',
            field=models.BooleanField(default=False, help_text='I consent to being photographed for social media and website use.'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='medical_accessibility_notes',
            field=models.TextField(blank=True, help_text='Optional: Please share any health, medical, or accessibility requirements (e.g., mobility needs, severe allergies) that the committee should be aware of to support you during rehearsals and events.', null=True),
        ),
    ]
