# Generated by Django 6.0.6 on 2026-06-24 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0006_memberprofile_consent_audio_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoirCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('ALL', 'All Active Members'), ('SOP', 'Sopranos Only'), ('ALT', 'Altos Only'), ('TEN', 'Tenors Only'), ('BAS', 'Basses Only')], default='ALL', max_length=3)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='The body of your email.')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
