# Generated by Django 6.0.6 on 2026-06-24 09:55

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0007_choircommunication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choircommunication',
            name='message',
            field=tinymce.models.HTMLField(help_text='The body of your email.'),
        ),
    ]
