# Generated by Django 6.0.6 on 2026-06-26 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0008_alter_choircommunication_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., AGM Minutes - June 2026', max_length=200)),
                ('doc_type', models.CharField(choices=[('MIN', 'Meeting Minutes'), ('POL', 'Policy / Governance'), ('FIN', 'Financial Report'), ('GEN', 'General Document')], default='MIN', max_length=3)),
                ('file', models.FileField(upload_to='committee_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
