# Generated by Django 6.0.6 on 2026-06-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0009_committeedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='notes',
            field=models.TextField(blank=True, help_text="e.g., 'Paid half in cash, remainder to be transferred'", null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Online (Stripe/Card)'), ('CASH', 'Cash'), ('BACS', 'Bank Transfer (BACS)'), ('MIX', 'Mixed / Other')], default='BACS', max_length=4),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Stripe PaymentIntent ID or Cheque Number', max_length=255, null=True),
        ),
    ]
