# Generated by Django 6.0.6 on 2026-06-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0010_subscriptionpayment_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_under_18',
            field=models.BooleanField(default=False),
        ),
    ]
