# Generated by Django 6.0.6 on 2026-06-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0011_memberprofile_is_under_18'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='is_exempt_from_subs',
            field=models.BooleanField(default=False, help_text='Exempts member from the termly financial ledger (e.g., scholars, bursaries, staff).'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='is_under_18',
            field=models.BooleanField(default=False, help_text='Flags member for safeguarding and duty of care protocols.'),
        ),
    ]
