# Generated by Django 6.0.6 on 2026-07-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0012_memberprofile_is_exempt_from_subs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repertoire',
            name='slug',
        ),
    ]
