# Generated by Django 6.0.6 on 2026-07-20 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0018_project_repertoire_and_remove_event_pieces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='e.g., Are you available the weekend of 14-15 March 2027?', max_length=200)),
                ('proposed_date', models.DateField(blank=True, help_text='Optional - the specific date being tested.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Extra context for members, e.g. venue under consideration.')),
                ('is_open', models.BooleanField(default=True, help_text='Closes the poll to new or changed responses once the committee has decided.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polls', to='choir.project')),
            ],
            options={
                'ordering': ['proposed_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('YES', 'Available'), ('NO', 'Not Available'), ('MAYBE', 'Maybe')], max_length=5)),
                ('notes', models.CharField(blank=True, help_text="Optional - e.g. 'Away until the 10th, fine after that.'", max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='choir.availabilitypoll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('poll', 'user')},
            },
        ),
    ]
