# Generated by Django 6.0.6 on 2026-08-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0019_availability_polling'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftAidDeclaration',
        ),
    ]
