"""
Django settings for clent_consort_site project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 1. Force load the .env file using the Path object
env_path = BASE_DIR / ".env"
load_dotenv(env_path)

# 2. Fetch the variables
SECRET_KEY = os.environ.get("SECRET_KEY")
DEBUG = os.environ.get("DEBUG", "False") == "True"

# 3. Add a hard-stop safety check so you know exactly if the file loaded
if not SECRET_KEY:
    raise ValueError(
        f"No SECRET_KEY found. Check that your .env file exists at {env_path}"
    )

# ==============================================================================
# DEPLOYMENT SECURITY SETTINGS
# ==============================================================================

if DEBUG:
    ALLOWED_HOSTS = [
        "127.0.0.1",
        "localhost",
    ]
else:
    # PRODUCTION: Maximum armor activated
    ALLOWED_HOSTS = [
        "clent-consort-app.onrender.com",
        "clentconsort.org",
        "www.clentconsort.org",
    ]

    # Force cookies to only travel over encrypted HTTPS connections
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Tell Django that Render's proxy is handling the SSL certificates safely
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # --- INVITATIONS BEFORE ALLAUTH ---
    "invitations",
    # --- ADD THESE FOR ALLAUTH ---
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "storages",  # For AWS S3 storage
    # Your apps...
    "anymail",
    "choir",
]

# Required by allauth to identify which database site it is managing
SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "clent_consort_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Tell Django to check this specific folder BEFORE looking at third-party packages
        "DIRS": [BASE_DIR / "choir" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "clent_consort_site.wsgi.application"


# ==============================================================================
# DATABASE CONFIGURATION (SQLite Local vs PostgreSQL Production)
# ==============================================================================

if DEBUG:
    # LOCAL DEVELOPMENT: Safely use the offline SQLite file
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    # PRODUCTION: Maximum strictness.
    # If DATABASE_URL is missing from Render, this will intentionally crash the build
    # to protect you from accidentally saving live data to a temporary file.
    DATABASES = {
        "default": dj_database_url.parse(
            os.environ.get("DATABASE_URL"), conn_max_age=600, ssl_require=True
        )
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
# The absolute path where Django will collect ALL static files for production
STATIC_ROOT = BASE_DIR / "staticfiles"


# ==========================================================================
# AUTHENTICATION ROUTING CONTROLS
# ==========================================================================
# Where to redirect users if they try to access a locked page:
LOGIN_URL = "account_login"

# Where to send users immediately after a successful login:
LOGIN_REDIRECT_URL = "members"

# Where to send users immediately after logging out:
LOGOUT_REDIRECT_URL = "home"

# ==============================================================================
# EMAIL CONFIGURATION
# ==============================================================================

if DEBUG:
    # LOCAL DEVELOPMENT: Keep printing to the terminal
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = "Clent Consort <hello@clentconsort.org>"
else:
    # PRODUCTION: Bypass Render's SMTP firewall via Brevo HTTP API
    EMAIL_BACKEND = "anymail.backends.brevo.EmailBackend"

    # Read the secure API credential from Render's environment
    ANYMAIL = {
        "BREVO_API_KEY": os.environ.get("BREVO_API_KEY"),
    }

    # The official address your choir members will see
    DEFAULT_FROM_EMAIL = "Clent Consort <hello@clentconsort.org>"

# Add so views.py can find it
CHOIR_CONTACT_EMAIL = "hello@clentconsort.org"

# ==============================================================================
# AUTHENTICATION & ALLAUTH CONFIGURATION
# ==============================================================================
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Needed to login to Django Admin
    "allauth.account.auth_backends.AuthenticationBackend",  # Needed for member login
]

# Modern Allauth configuration for Django 6.x
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

# Require members to click the link in their email before gaining access
ACCOUNT_EMAIL_VERIFICATION = "mandatory"

# Where to send the user after they successfully log in or log out
LOGIN_REDIRECT_URL = "members"  # Assuming your dashboard url name is 'members'
ACCOUNT_LOGOUT_REDIRECT_URL = "home"

# ==============================================================================
# SECURE INVITATION PROTOCOL
# ==============================================================================
# Tell Allauth to use the Invitations system to handle signups
ACCOUNT_ADAPTER = "invitations.models.InvitationsAdapter"

# Completely disable the public registration form
INVITATIONS_INVITE_ONLY = True

# Automatically accept the invitation token once they finish setting their password
INVITATIONS_ACCEPT_INVITE_AFTER_SIGNUP = True

# ==============================================================================
# MEDIA STORAGE CONFIGURATION (AWS S3)
# ==============================================================================
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")

# Temporary print to prove the .env is connected
print("=== CLOUD CHECK ===")
print("Bucket:", AWS_STORAGE_BUCKET_NAME)
print("Key Found:", bool(AWS_ACCESS_KEY_ID))
print("===================")

# Only activate AWS storage if we have supplied real keys
if AWS_ACCESS_KEY_ID and AWS_ACCESS_KEY_ID != "pending_verification_id":
    # Modern Django 5.0+ Cloud Storage Configuration
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

    AWS_S3_REGION_NAME = "eu-north-1"  # Stockholm
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_QUERYSTRING_AUTH = True
    AWS_S3_FILE_OVERWRITE = False
else:
    # Modern Django 5.0+ Local Storage Configuration
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
