"""
Django settings for clent_consort_site project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 1. Force load the .env file using the Path object
env_path = BASE_DIR / ".env"
load_dotenv(os.path.join(BASE_DIR, ".env"))

# 2. Fetch the variables
SECRET_KEY = os.environ.get("SECRET_KEY")
DEBUG = os.environ.get("DEBUG") == "True"

# 3. Add a hard-stop safety check so you know exactly if the file loaded
if not SECRET_KEY:
    raise ValueError(
        f"No SECRET_KEY found. Check that your .env file exists at {env_path}"
    )

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # --- ADD THESE FOR ALLAUTH ---
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "storages",  # For AWS S3 storage
    # Your apps...
    "choir",
]

# Required by allauth to identify which database site it is managing
SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "clent_consort_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "clent_consort_site.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/London"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# ==========================================================================
# AUTHENTICATION ROUTING CONTROLS
# ==========================================================================
# Where to redirect users if they try to access a locked page:
LOGIN_URL = "account_login"

# Where to send users immediately after a successful login:
LOGIN_REDIRECT_URL = "members"

# Where to send users immediately after logging out:
LOGOUT_REDIRECT_URL = "home"

# ==============================================================================
# EMAIL CONFIGURATION
# ==============================================================================

# The address that will receive the contact form submissions.
# TODO: Update this when the official choir email is created.
CHOIR_CONTACT_EMAIL = "placeholder@clentconsort.com"

# For development: Forces Django to print emails to the terminal instead of sending them.
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# The address the server uses to send the email (must be defined, even if dummy)
DEFAULT_FROM_EMAIL = "noreply@clentconsort.com"

# ==============================================================================
# AUTHENTICATION & ALLAUTH CONFIGURATION
# ==============================================================================
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # Needed to login to Django Admin
    "allauth.account.auth_backends.AuthenticationBackend",  # Needed for member login
]

# Modern Allauth configuration for Django 6.x
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

# Require members to click the link in their email before gaining access
ACCOUNT_EMAIL_VERIFICATION = "mandatory"

# Where to send the user after they successfully log in or log out
LOGIN_REDIRECT_URL = "members"  # Assuming your dashboard url name is 'members'
ACCOUNT_LOGOUT_REDIRECT_URL = "home"

# ==============================================================================
# MEDIA STORAGE CONFIGURATION (AWS S3)
# ==============================================================================
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")

# Temporary print to prove the .env is connected
print("=== CLOUD CHECK ===")
print("Bucket:", AWS_STORAGE_BUCKET_NAME)
print("Key Found:", bool(AWS_ACCESS_KEY_ID))
print("===================")

# Only activate AWS storage if we have supplied real keys
if AWS_ACCESS_KEY_ID and AWS_ACCESS_KEY_ID != "pending_verification_id":
    # Modern Django 5.0+ Cloud Storage Configuration
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

    AWS_S3_REGION_NAME = "eu-north-1"  # Stockholm
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_QUERYSTRING_AUTH = True
    AWS_S3_FILE_OVERWRITE = False
else:
    # Modern Django 5.0+ Local Storage Configuration
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
